apiVersion: v1
kind: Secret
metadata:
  name: datasource-connection-info
type: Opaque
data:
  db-password: 
  db-username: 
  db-url: 
  
# Example secret file that matches the expected structure for passing DB info to application