apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-test-service
  labels:
    app: failover-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failover-test-service
  template:
    metadata:
      labels:
        app: failover-test-service
    spec:
      containers:
      - name: failover-test-service
        image:  us.icr.io/wkorando/postgres-failover:8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.type
          value: org.apache.tomcat.jdbc.pool.DataSource
        - name: spring.datasource.username
          value: "<>"
        - name: spring.datasource.password
          value: "<>"
        - name: spring.datasource.tomcat.max-active
          value: "20"
        - name: spring.datasource.tomcat.min-idle
          value: "10"
        - name: spring.datasource.tomcat.test-on-borrow
          value: "true"
        - name: spring.datasource.tomcat.test-on-connect
          value: "true"
        - name: spring.datasource.tomcat.test-on-return
          value: "true"
        - name: spring.datasource.tomcat.test-while-idle
          value: "true"
        - name: spring.datasource.tomcat.validation-query
          value: "SELECT 1"
        - name: spring.datasource.tomcat.validation-interval
          value: "60"
        - name: spring.datasource.tomcat.validation-query-timeout
          value: "5"
        - name: spring.datasource.tomcat.remove-abandoned
          value: "true"
        - name: spring.datasource.tomcat.remove-abandoned-timeout
          value: "60"
        - name: spring.datasource.url
          value: "jdbc:postgresql://<>/ibmclouddb?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory"
#        - name: spring.datasource.hikari.data-source-properties.socketTimeout
#          value: "60"
#        - name: JAVA_OPTS
#          value: -Dsun.net.inetaddr.ttl=60 
---
apiVersion: v1
kind: Service
metadata:
  name: failover-test-port
spec:
  type: NodePort
  selector:
    app: failover-test-service
  ports:
    - port: 8080
      name: http    