apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-test-service
  labels:
    app: failover-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failover-test-service
  template:
    metadata:
      labels:
        app: failover-test-service
    spec:
      containers:
      - name: failover-test-service
        image:  wkorando/postgres-failover-test:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.hikari.maximum-pool-size
          value: "25"
        - name: spring.datasource.hikari.max-lifetime
          value: "60000"
        - name: spring.datasource.username
          value: "<>"
        - name: logging.level.org.springframework.boot.actuate
          value: DEBUG  
        - name: logging.level.org.springframework
          value: ERROR  
        - name: logging.level.com.zaxxer.hikari
          value: DEBUG
        - name: spring.datasource.password
          value: "<>"
        - name: spring.datasource.url
          value: "jdbc:postgresql://,./ibmclouddb?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory"
#        - name: spring.datasource.hikari.data-source-properties.socketTimeout
#          value: "60"
#        - name: JAVA_OPTS
#          value: -Dsun.net.inetaddr.ttl=60 
---
apiVersion: v1
kind: Service
metadata:
  name: failover-test-port
spec:
  type: NodePort
  selector:
    app: failover-test-service
  ports:
    - port: 8080
      name: http    