apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-test-service
  labels:
    app: failover-test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failover-test-service
  template:
    metadata:
      labels:
        app: failover-test-service
    spec:
      containers:
      - name: failover-test-service
        image:  wkorando/postgres-failover:boot-15-2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /management/health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: management.endpoints.web.base-path
          value: "/management"
        - name: spring.datasource.hikari.maximum-pool-size
          value: "25"
        - name: spring.datasource.hikari.max-lifetime
          value: "60000"
        - name: logging.level.org.springframework
          value: ERROR  
        - name: logging.level.com.zaxxer.hikari
          value: DEBUG
        - name: spring.datasource.type
          value: com.zaxxer.hikari.HikariDataSource
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: datasource-connection-info
              key: db-username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: datasource-connection-info
              key: db-password
        - name: spring.datasource.url
          valueFrom:
            secretKeyRef:
              name: datasource-connection-info
              key: db-url
---
apiVersion: v1
kind: Service
metadata:
  name: failover-test-port
spec:
  type: NodePort
  selector:
    app: failover-test-service
  ports:
    - port: 8080
      name: http   
      