apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-test-service-health-probe
  labels:
    app: failover-test-service-health-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failover-test-service-health-probe
  template:
    metadata:
      labels:
        app: failover-test-service-health-probe
    spec:
      containers:
      - name: failover-test-service
        image:  wkorando/postgres-failover:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 2
          failureThreshold: 1
        env:
        - name: management.endpoints.web.base-path
          value: "/management"
        - name: spring.datasource.hikari.maximum-pool-size
          value: "25"
        - name: spring.datasource.hikari.max-lifetime
          value: "60000"
        - name: logging.level.org.springframework
          value: ERROR  
        - name: logging.level.com.zaxxer.hikari
          value: DEBUG
        - name: spring.datasource.username
          value: "<>"
        - name: spring.datasource.password
          value: "<>"
        - name: spring.datasource.url
          value: "jdbc:postgresql://<>/ibmclouddb?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory"
---
apiVersion: v1
kind: Service
metadata:
  name: failover-test-port-health-probe
spec:
  type: NodePort
  selector:
    app: failover-test-service-health-probe
  ports:
    - port: 8080
      name: http   
      